### ISSUE TITLE
Iconsistent naming

### ISSUE THREAD

**Issue by AHeiming** [Ditectrev/Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers#18]
Hi,

I recognized that some questions are inconsistent with the naming. In the upper half, the Developers are named "Developers", further on  they are referred to as "The Development Team". 
I don't know, if this is on purpose, if so, I'm sorry for misunderstanding!

Best regards
Alex

**Comment by danieldanielecki** [comment]
@AHeiming, thanks for asking :)

That's not a mistake because the Development Team refers to the Developers, Scrum Master, and Product Owner.
The Development Team is interchangeably used with Scrum Team tho, and that's not a mistake either.

Hope it helps; I'm closing the issue.

**Comment by danieldanielecki** [comment]
It needs to be reopened and 5x "Development Team" needs to be changed with "Developers".

In my previous answer, I mistakenly confused "Development Team" with "Scrum Team".

**Comment by danieldanielecki** [comment]
Let's park for now the issue and see if there'll be a similar feedback in other `Scrum` courses as well as it needs to be find out whether just these keywords have changed, or the questions simply became obsolete.

**Comment by rcmedeiros** [comment]
This wording change got me confused too. I first learned that the Scrum Team is the Development Team plus Scrum Master and Product Owner. Sometime along the way they updated the concept to discourage sub-grouping. Now there's only The Scrum Team, comprised of Developers, Product Owner and Scrum Master.

References:
https://scrumguides.org/scrum-guide.html#scrum-team
https://www.scrum.org/forum/scrum-forum/45339/development-team-vs-developers-new-scrum-guide

**Comment by danieldanielecki** [comment]
@rcmedeiros, can you please create a Pull Request for this change?

**Comment by danieldanielecki** [comment]
> Change also `self organizing` to `self managing`.

No, this one we don't replace. The guide has replaced it, but it doesn't matter: self-Organizing is only one aspect of self-Managing. Self-managing is much more than just how they organize.

**Comment by danieldanielecki** [comment]
> > Change also `self organizing` to `self managing`.
> 
> No, this one we don't replace. The guide has replaced it, but it doesn't matter: self-Organizing is only one aspect of self-Managing. Self-managing is much more than just how they organize.

actually, let's just do it, so we have it adjusted...

**Comment by danieldanielecki** [comment]
> Hi,
> 
> I recognized that some questions are inconsistent with the naming. In the upper half, the Developers are named "Developers", further on they are referred to as "The Development Team". I don't know, if this is on purpose, if so, I'm sorry for misunderstanding!
> 
> Best regards Alex

fixed in https://github.com/Ditectrev/Scrum-Developer-I-PSD-I-Practice-Tests-Exams-Questions-Answers/commit/36b0262999b261aa4e2a38e7ee5d661220913cdb, finally closing!
